image: Ubuntu1804 #образ для сборки
stack: node 12    # окружение
branches:
      only:
        - master  # ветка git
cache: node_modules #кеширование откуда беруться пакеты
install:
    - npm install   # команда установки зависимостей
build: off    # нет сборки нет webpack
test_script:
    - npm run lint && npm test # скрипт сборки 
